# Copyright 2006-2021 VMware, Inc.
# SPDX-License-Identifier: MIT
---
- name: "ensure wildcard tls secret exists {{ namespace }}/{{ secret }}"
  import_role:
    name: "common/manifest-file"
  vars:
    manifest_description: "wildcard certificate"
    manifest_template:    "secret-wildcard.yaml.j2"
    manifest_file:        "secret-wildcard.yaml"
    manifest_staging_dir: "{{ tanzu_security.staging_dir }}/certificates"
