# Copyright 2006-2021 VMware, Inc.
# SPDX-License-Identifier: MIT
---
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
kubeadmConfigPatches:
  - |
    apiVersion: kubeadm.k8s.io/v1beta2
    kind: ClusterConfiguration
    networking:
      disableDefaultCNI: true
      podSubnet: 192.168.0.0/16
    metadata:
      name: config
    apiServer:
      extraArgs:
        "enable-admission-plugins": "NamespaceLifecycle,LimitRanger,ServiceAccount,TaintNodesByCondition,Priority,DefaultTolerationSeconds,DefaultStorageClass,PersistentVolumeClaimResize,MutatingAdmissionWebhook,ValidatingAdmissionWebhook,ResourceQuota"
networking:
  apiServerAddress: 127.0.0.1
nodes:
  - role: worker
    image: kindest/node:v1.19.1
    extraPortMappings:
      - containerPort: 80
        hostPort: 80
        protocol: TCP
        listenAddress: "0.0.0.0"
      - containerPort: 443
        hostPort: 443
        protocol: TCP
        listenAddress: "0.0.0.0"
  - role: worker
    image: kindest/node:v1.19.1
  - role: worker
    image: kindest/node:v1.19.1
  - role: control-plane
    image: kindest/node:v1.19.1
