# Copyright 2006-2021 VMware, Inc.
# SPDX-License-Identifier: MIT
---
- name: "ensure the namespace is removed"
  import_role:
    name: "common/namespace/clean"
  vars:
    namespace: "{{ tanzu_spring_cloud_gateway.namespace }}"

- name: "ensure the cluster-wide resources are removed"
  k8s:
    state:   "absent"
    context: "{{ tanzu_kubectl_context }}"
    kind:    "{{ item.kind }}"
    name:    "{{ item.name }}"
  with_items:
    - name: "scg-operator-resources-role-binding"
      kind: "ClusterRoleBinding"
    - name: "scg-operator-resources-role"
      kind: "ClusterRole"

- name: "ensure all spring cloud gateway custom resource definitions have been removed"
  k8s:
    state:   "absent"
    kind:    "CustomResourceDefinition"
    name:    "{{ item }}"
    context: "{{ tanzu_kubectl_context }}"
  register: _resource_status
  until:    not _resource_status.failed
  retries:  30
  delay:    1
  with_items:
    - "springcloudgateways.tanzu.vmware.com"
    - "springcloudgatewaymappings.tanzu.vmware.com"
    - "springcloudgatewayrouteconfigs.tanzu.vmware.com"
