# Copyright 2006-2021 VMware, Inc.
# SPDX-License-Identifier: MIT
---
tanzu_spring_cloud_gateway:
  # common vars
  namespace:   "tanzu-spring-cloud-gateway"
  staging_dir: "{{ rpk_staging_dir }}/tanzu-spring-cloud-gateway"

  demo:
    dns: spring-cloud-gateway-demo.{{ tanzu_ingress_domain }}

  pivnet:
    version: "1.0.0"
    download_url: https://network.pivotal.io/api/v2/products/spring-cloud-gateway-for-kubernetes/releases/835308/product_files/891162/download
    download_sha: "2420f5d32d3ee545cf4eaee10fe6730ed28130e03e5b04c19e5d25d50b0ff2ee"

  registry:
    project:
      project_name:  "spring-cloud-gateway"
      metadata:
        auto_scan:   "false"
        public:      "false"
    destination_tag: "rpk-1.0"
    images:
      - name: "scg-operator"
        tag:  "1.0.0"
      - name: "gateway"
        tag:  "1.0.0"

  # use namespace operator or not
  workload_tenancy:
    enabled: false
