---
name: "Unit Test"
on:
  - "push"
  # pull_request:
  #   branches:
  #     - develop
jobs:

  detect-file-changes:
    name: "Detect File Changes"
    runs-on: "ubuntu-latest"
    steps:
      - name: "Checkout Code"
        uses: "actions/checkout@v2"
        with:
          fetch-depth: 2
      - name: "Detect File Changes"
        uses: "tj-actions/verify-changed-files@v5.3"
        id: "changed-files"
      - name: List all modified files
        run: |
          for file in "${CHANGED}"; do
            echo "$file was modified"
          done
        env:
          CHANGED: ${{ steps.changed-files.outputs.all_modified_files }}
    outputs:
      changed-files: ${{ steps.changed-files.outputs.all_modified_files }}
      changed: ${{ steps.changed-files.outputs.files_changed }}

  # TODO: hard-coded for now; find a way to make this dynamic
  unit-test-autoscaling:
    name: "Unit Test Autoscaling"
    runs-on: "ubuntu-latest"
    needs: "detect-file-changes"
    steps:
      - name: "Checkout Code"
        uses: "actions/checkout@v2"
      - uses: "./.github/action-unit-test"
        if: "needs.detect-file-changes.changed == 'true'"
        with:
          component: "autoscaling"

  unit-test-workload-tenancy:
    name: "Unit Test Workload Tenancy"
    runs-on: "ubuntu-latest"
    needs: "detect-file-changes"
    steps:
      - name: "Checkout Code"
        uses: "actions/checkout@v2"
      - uses: "./.github/action-unit-test"
        if: "needs.detect-file-changes.changed == 'true'"
        with:
          component: "workload-tenancy"
