---
name: Unit Test
on:
  - push
  # pull_request:
  #   branches:
  #     - develop
jobs:

  # TODO: hard-coded for now; find a way to make this dynamic
  unit-test-workload-tenancy:
    name: Unit Test Workload Tenancy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@master
      - name: Initialize KIND Cluster
        uses: container-tools/kind-action@v1
        with:
          cluster_name: rpk-kind
          kubectl_version: v1.20.0
          version: v0.10.0
          config: ci/clusters/kind-cluster-config-unit.yaml
      - name: Build the Image
        run: make build
      - name: Setup KIND Cluster
        run: make setup.kind && make setup.kind.network
      - name: Deploy the Component
        run: |
          ROLE=workload-tenancy \
          CUSTOM_RPK_ARGS="-e '-e tanzu_default_tls_provider=ca \
                           -e tanzu_provider=kind \
                           -e tanzu_networking_ipip_mode=Always \
                           -e tanzu_kubectl_context=kind-rpk-kind \
                           -e tanzu_dns_provider=xip.io \
                           -e ingress_ip=127.0.0.1 \
                           -e tanzu_ingress_domain=127.0.0.1.xip.io \
                           -e tanzu_cluster_name=kind-rpk-kind \
                           -e tanzu_mission_control_cluster_group=rpk-clusters'" \
          make deploy.role
