---
name: Unit Test
on:
  - push
  # pull_request:
  #   branches:
  #     - develop
jobs:

  # TODO: hard-coded for now; find a way to make this dynamic
  unit-test-workload-tenancy:
    name: Unit Test Workload Tenancy
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/action-unit-test
